### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by mirodietiker** [actoteam/sketch-drupal-theme-seven#8]
We need an exmple for the Overlay.

**Comment by NemanjaTck** [comment]
Here is the screenshot of the overlay from Drupal 7. 
https://www.drupal.org/files/overlay.png
There is an issue in development of Drupal 8 where overlay is completely removed - https://www.drupal.org/node/2088121
Should we still consider adding it as an element?

**Comment by NemanjaTck** [comment]
With input from Sascha, I am changing the title and removing META since it will be one element and one issue. To open the dialog go to Structure->Views and click on any of the links on the left side. 
![dialog](https://cloud.githubusercontent.com/assets/3010324/19241123/7570d5c4-8f0d-11e6-870b-188d98d626cf.png)

**Comment by NemanjaTck** [comment]
Proposed idea is to introduce overlay through the Jquery collection. There are already Jquery collections made for Sketch app, source: http://designmodo.com/gui-sketch-app/

**Comment by NenadSC** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/18460472/19427611/616ba21a-9445-11e6-928e-f8225ab5427e.png)
